package com.enroll.merchantN.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class MasterDto {
    private String onboarding;
    private String mccCode;
    private String type;
    private String tier;
    private String riskGrade;
    private String businessLocation;
    private String continent;
    private String region;
    private String country;
    private String city;
    private String district;
    private String street;
    private String ward;
    private String plot;
    private String address;
    private String landmark;
    private String locationPin;
    private String coordinates;
    private String postalCode;
    private String poBox;
    private String issuer;
    private String acquirer;
    private String fsp;
    private String gateway;
    private String aggregator;
    private String subAggregator;
    private String merchantSegment;
    private String wallet;
    private String walletType;
    private String hierarchy;
    private String role;
    private String accessPrivilege;
    private String merchantType;
    private String userNamePrefix;
    private String merchantName;
    private String representativeName;
    private String contactDetails;
    private String email;
    private String simNumber;
    private String walletNumMsisdn;
    private String tillNumber;
    private String hierarchyType;
    private String hierarchyLevel;
    private String locationPinSecondary;
    private String website;
    private String whatsapp;
    private String telegram;
    private String instagram;
    private String facebook;
    private String twitter;
    private String tiktok;
    private String social01;
    private String social02;
    private String social03;
    private String logo;
    private String preferredLanguage;
    private String businessNameDisplay;
    private String tradingName;
    private String idType;
    private String registrationCertificate;
    private String tin;
    private String vrn;
    private String license;
    private String director;
    private String directorId;
    private String bankType;
    private String bankCountry;
    private String currency;
    private String bankName;
    private String accountName;
    private String accountNumber;
    private String bankAddress;
    private String bankContact;
    private String swift;
    private String iban;
    private String minLimit;
    private String maxLimit;
    private String dayLimit;
    private String serviceFeeType;
    private String tariffGrade;
    private String others;
    private String createdOn;
    private String networkCode;
    private String autoSweepAllowed;
}
